import type { Exercise, WorkoutDefinition, ScheduleDay } from '../types';

export const EXERCISES: Exercise[] = [
  // ─── WORKOUT A: PUSH (home dumbbells) ───────────────────────────────────────
  {
    id: 'dumbbell-floor-press',
    name: 'Dumbbell Floor Press',
    primaryMuscles: ['chest', 'triceps', 'shoulders'],
    equipment: 'dumbbell',
    defaultSets: 4,
    repRange: '8-12',
    tempo: '2s down / 1s pause / 1s up',
    cues: [
      'Lie flat on your back with knees bent and feet flat on the floor.',
      'Hold a dumbbell in each hand at chest level, elbows at roughly 45° from your torso.',
      'Press the dumbbells up until arms are almost fully extended — keep a soft elbow lock.',
      'Lower under control until your triceps touch the floor, then pause briefly.',
      'Drive the weight back up, squeezing the chest at the top.',
      'Keep your lower back neutral — avoid arching excessively off the floor.',
    ],
    commonMistakes: [
      'Flaring elbows too wide — puts stress on the shoulder joint.',
      'Bouncing triceps off the floor instead of pausing — reduces time under tension.',
      'Rushing the eccentric (lowering) phase — slow it down to 2 seconds.',
      'Letting the dumbbells drift apart at the top — keep them tracking over your mid-chest.',
    ],
    animationKeyframes: [
      'Starting position: lying flat, dumbbells at chest, elbows on floor.',
      'Press phase: dumbbells rise, arms extend, chest contracts.',
      'Top position: arms near-extended, brief squeeze.',
      'Lowering phase: slow descent, elbows return to floor.',
    ],
    animationUrl: null,
  },
  {
    id: 'dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    primaryMuscles: ['shoulders', 'triceps'],
    equipment: 'dumbbell',
    defaultSets: 4,
    repRange: '8-12',
    tempo: '2s down / 1s up',
    cues: [
      'Sit or stand with a dumbbell in each hand at shoulder height, palms forward.',
      'Brace your core and maintain a neutral spine throughout the movement.',
      'Press the dumbbells overhead until arms are fully extended — do not lock out hard.',
      'At the top, the dumbbells should be directly over your shoulders.',
      'Lower slowly back to shoulder height over 2 seconds.',
      'Avoid shrugging your traps — keep shoulders packed down.',
    ],
    commonMistakes: [
      'Arching the lower back to compensate for limited shoulder mobility.',
      'Letting elbows flare too far forward — think "goalpost" arm position.',
      'Partial reps — go through full range of motion each rep.',
      'Using momentum to swing the weight up instead of strict pressing.',
    ],
    animationKeyframes: [
      'Start: dumbbells at shoulder height, elbows bent at 90°.',
      'Press: arms extend overhead, dumbbells converge slightly.',
      'Top: arms extended, brief pause.',
      'Lower: controlled descent back to shoulder height.',
    ],
    animationUrl: null,
  },
  {
    id: 'dumbbell-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    primaryMuscles: ['shoulders'],
    equipment: 'dumbbell',
    defaultSets: 3,
    repRange: '12-15',
    tempo: '1s up / 2s down',
    cues: [
      'Stand with dumbbells at your sides, palms facing inward.',
      'With a slight bend in the elbows, raise the dumbbells out to the sides until upper arms are parallel to the floor.',
      'Lead with your elbows, not your wrists — imagine pouring a pitcher of water.',
      'At the top, your pinkies should be slightly higher than your thumbs.',
      'Lower slowly over 2 seconds — the negative is where the growth happens.',
      'Avoid shrugging — keep neck long and shoulders down.',
    ],
    commonMistakes: [
      'Using too much weight and swinging / cheating with the torso.',
      'Raising above shoulder height — you lose side-delt activation.',
      'Dropping the weight too fast — slow eccentric is essential.',
      'Internal rotation of the wrist (thumbs up) — slightly externally rotate.',
    ],
    animationKeyframes: [
      'Start: arms at sides, slight elbow bend.',
      'Raise: arms sweep out laterally, dumbbells rise to shoulder height.',
      'Top: arms parallel to floor, brief pause.',
      'Lower: controlled 2-second descent back to sides.',
    ],
    animationUrl: null,
  },
  {
    id: 'dumbbell-floor-fly',
    name: 'Dumbbell Floor Fly',
    primaryMuscles: ['chest'],
    equipment: 'dumbbell',
    defaultSets: 3,
    repRange: '12',
    tempo: '3s down / 1s up',
    cues: [
      'Lie on your back with knees bent, holding dumbbells directly above your chest with palms facing each other.',
      'Keep a slight, fixed bend in your elbows throughout the entire movement.',
      'Lower the dumbbells in a wide arc, stretching the chest over 3 seconds.',
      'Stop when your upper arms touch the floor — do not force the stretch.',
      'Squeeze the chest to bring the dumbbells back up in the same arc.',
      'Think of it like hugging a giant tree — arc, not press.',
    ],
    commonMistakes: [
      'Bending the elbows too much — turns it into a press, not a fly.',
      'Going too heavy — your chest will thank you for lighter weights here.',
      'Rushing the stretch phase — the 3-second negative is the point.',
      'Losing the arc path and pressing straight up.',
    ],
    animationKeyframes: [
      'Start: dumbbells together above chest, palms facing.',
      'Open: arms arc out and down, chest stretches.',
      'Bottom: upper arms near floor, maximum chest stretch.',
      'Close: arms sweep back up in arc, chest contracts.',
    ],
    animationUrl: null,
  },
  {
    id: 'dumbbell-overhead-triceps-extension',
    name: 'Dumbbell Overhead Triceps Extension',
    primaryMuscles: ['triceps'],
    equipment: 'dumbbell',
    defaultSets: 4,
    repRange: '10-12',
    tempo: '2s down / 1s up',
    cues: [
      'Sit or stand holding one dumbbell with both hands, gripping the inner plate (diamond grip).',
      'Raise the dumbbell overhead with arms fully extended.',
      'Keeping your upper arms pinned to your ears, lower the dumbbell behind your head.',
      'Lower until you feel a deep stretch in your triceps — elbows point to the ceiling.',
      'Drive the dumbbell back up to full extension, squeezing the triceps.',
      'Keep your core braced — avoid arching the lower back.',
    ],
    commonMistakes: [
      'Flaring the elbows out to the sides — keep them pointing forward.',
      'Moving the upper arms — only the forearms should hinge at the elbow.',
      'Using too much weight and losing control on the descent.',
      'Short-changing the range — go for the full stretch behind your head.',
    ],
    animationKeyframes: [
      'Start: dumbbell overhead, arms extended, elbows at ears.',
      'Lower: forearms hinge back, dumbbell descends behind head.',
      'Stretched position: maximum tricep stretch, elbows still pointing up.',
      'Extend: drive weight back overhead, triceps contract.',
    ],
    animationUrl: null,
  },
  {
    id: 'dumbbell-triceps-kickback',
    name: 'Dumbbell Triceps Kickback',
    primaryMuscles: ['triceps'],
    equipment: 'dumbbell',
    defaultSets: 3,
    repRange: '12-15',
    tempo: '1s back / 2s return',
    cues: [
      'Hinge forward at the hips until your torso is nearly parallel to the floor.',
      'Tuck your upper arm firmly against your side, elbow bent at 90°.',
      'Keeping your upper arm pinned, extend your forearm straight back.',
      'At full extension, squeeze the tricep hard for a moment.',
      'Return the forearm slowly over 2 seconds back to the start.',
      'Perform all reps on one arm before switching.',
    ],
    commonMistakes: [
      'Swinging the upper arm — it must stay glued to your side.',
      'Not reaching full extension — partial reps limit the contraction.',
      'Using momentum to kick the weight back rather than muscular contraction.',
      'Rounding the lower back — maintain a flat back hinge position.',
    ],
    animationKeyframes: [
      'Start: bent over, upper arm parallel to floor, forearm hanging down.',
      'Kick back: forearm extends backward, arm straightens.',
      'Top: arm fully extended, tricep contracted, brief squeeze.',
      'Return: forearm swings back down slowly.',
    ],
    animationUrl: null,
  },

  // ─── WORKOUT B: PULL (gym machines) ─────────────────────────────────────────
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    primaryMuscles: ['lats', 'back'],
    equipment: 'machine',
    defaultSets: 4,
    repRange: '8-12',
    tempo: '1s down / 2s up',
    cues: [
      'Sit down and lock your thighs under the pad. Grip the bar just wider than shoulder-width, overhand.',
      'Lean back slightly (about 10-15°) and puff your chest up toward the bar.',
      'Initiate the pull by driving your elbows DOWN and BACK — not just pulling with your biceps.',
      'Pull the bar to your upper chest, squeezing your shoulder blades together at the bottom.',
      'Hold the contraction for a beat, then control the bar back up over 2 seconds.',
      'Let your shoulder blades rise and your lats stretch fully at the top.',
    ],
    commonMistakes: [
      'Pulling with biceps instead of elbows leading — think "elbows to hips".',
      'Leaning back excessively — turns it into a row, not a pulldown.',
      'Not reaching full stretch at the top — lat flexibility is built here.',
      'Using too much weight and using momentum to swing the bar down.',
    ],
    animationKeyframes: [
      'Start: arms extended overhead, lats stretched, slight back lean.',
      'Pull: elbows drive down, bar descends toward upper chest.',
      'Contact: bar touches chest, elbows tucked, scapulae retracted.',
      'Return: controlled ascent, arms extend, lats stretch again.',
    ],
    animationUrl: null,
  },
  {
    id: 'seated-cable-row',
    name: 'Seated Cable Row',
    primaryMuscles: ['back', 'lats', 'rear-delts'],
    equipment: 'cable',
    defaultSets: 4,
    repRange: '10-12',
    tempo: '1s pull / 2s return',
    cues: [
      'Sit upright on the cable row machine, feet on the platform, knees slightly bent.',
      'Hold the handle (neutral grip) with arms extended and torso upright.',
      'Initiate the pull by retracting your shoulder blades first.',
      'Row the handle to your lower sternum, keeping elbows close to your sides.',
      'Squeeze your back muscles hard at full contraction.',
      'Extend arms slowly over 2 seconds, allowing your shoulder blades to protract and stretch.',
    ],
    commonMistakes: [
      'Swinging the torso back to assist the pull — keep it upright.',
      'Pulling to the wrong height — aim for lower chest/sternum, not belly button.',
      'Not protracting at the start — you lose the full range and the stretch.',
      'Flaring elbows out wide — keep them tight to your body for better lat activation.',
    ],
    animationKeyframes: [
      'Start: torso upright, arms extended, scapulae protracted.',
      'Initiate: scapulae retract first, then elbows drive back.',
      'Contact: handle at sternum, elbows at sides, full contraction.',
      'Return: arms extend slowly, scapulae spread forward.',
    ],
    animationUrl: null,
  },
  {
    id: 'assisted-pull-up',
    name: 'Assisted Pull-Up',
    primaryMuscles: ['lats', 'biceps', 'back'],
    equipment: 'machine',
    defaultSets: 3,
    repRange: '10',
    tempo: '1s up / 2s down',
    cues: [
      'Set the machine to an assist weight that lets you do clean reps with good form.',
      'Grip the handles overhand, just wider than shoulder-width.',
      'Hang fully with arms extended, shoulders packed down (not shrugged).',
      'Drive your elbows down and back to pull your chin above the handles.',
      'Squeeze at the top, then lower yourself slowly over 2 seconds.',
      'As you get stronger, gradually reduce the assist weight.',
    ],
    commonMistakes: [
      'Kipping or using momentum — this defeats the purpose of the machine.',
      'Not reaching full extension at the bottom — work the full range.',
      'Pulling with the arms only instead of initiating with the back.',
      'Chin not clearing the bar — count a rep only when you get there.',
    ],
    animationKeyframes: [
      'Start: hanging at full extension, shoulders packed.',
      'Pull: elbows drive down, body rises.',
      'Top: chin above bar, chest near handles, peak contraction.',
      'Lower: slow controlled descent back to full hang.',
    ],
    animationUrl: null,
  },
  {
    id: 'face-pull',
    name: 'Face Pull',
    primaryMuscles: ['rear-delts', 'back'],
    equipment: 'cable',
    defaultSets: 3,
    repRange: '15',
    tempo: 'controlled',
    cues: [
      'Set the cable pulley to upper-chest height. Use a rope attachment.',
      'Hold the rope with palms facing inward, thumbs toward you.',
      'Step back so arms are extended, keeping your elbows high — at ear level.',
      'Pull the rope toward your face, separating your hands and rotating your shoulders externally.',
      'At full contraction, your thumbs should point behind you (external rotation).',
      'Return slowly with control — this builds rear-delt and rotator cuff health.',
    ],
    commonMistakes: [
      'Letting elbows drop — the high elbow position targets rear delts specifically.',
      'No external rotation at the end — squeeze and rotate, thumbs back.',
      'Going too heavy and compensating with body lean.',
      'Pulling to the chin instead of the face/forehead level.',
    ],
    animationKeyframes: [
      'Start: arms extended to cable, elbows high at ear level.',
      'Pull: rope comes toward face, elbows stay high.',
      'Contact: hands near ears, external rotation, thumbs back.',
      'Return: controlled extension back to start.',
    ],
    animationUrl: null,
  },
  {
    id: 'machine-biceps-curl',
    name: 'Machine Biceps Curl',
    primaryMuscles: ['biceps'],
    equipment: 'machine',
    defaultSets: 4,
    repRange: '10-12',
    tempo: '1s up / 2s down',
    cues: [
      'Adjust the seat so your upper arms rest comfortably on the pad at shoulder height.',
      'Grip the handles with a supinated (underhand) grip.',
      'Curl the handles up, squeezing the biceps at the top of the movement.',
      'Avoid shrugging or using shoulder momentum — isolate the bicep.',
      'Lower the weight slowly over 2 seconds to full extension.',
      'Feel the stretch at the bottom — do not let the stack rest between reps.',
    ],
    commonMistakes: [
      'Lifting the upper arms off the pad — removes isolation and cheats the curl.',
      'Not reaching full extension at the bottom — you lose the stretch.',
      'Going too fast on the way down — the eccentric is half the exercise.',
      'Gripping too tight — relax your grip slightly to feel more bicep activation.',
    ],
    animationKeyframes: [
      'Start: arms extended on pad, handles at bottom.',
      'Curl: handles rise, biceps contract, peak at top.',
      'Top: full curl, brief squeeze.',
      'Lower: slow controlled descent to full extension.',
    ],
    animationUrl: null,
  },
  {
    id: 'rope-hammer-curl',
    name: 'Rope Hammer Curl',
    primaryMuscles: ['biceps', 'forearms'],
    equipment: 'cable',
    defaultSets: 3,
    repRange: '12',
    tempo: '1s up / 2s down',
    cues: [
      'Set the low cable pulley and attach the rope. Stand facing the machine.',
      'Hold the rope with a neutral grip (palms facing each other), thumbs up.',
      'Stand up straight, curl the rope up keeping your elbows at your sides.',
      'Pull the ends of the rope apart slightly at the top for peak contraction.',
      'Lower slowly over 2 seconds — feel the brachialis stretch.',
      'Neutral grip places unique emphasis on the brachialis and brachioradialis.',
    ],
    commonMistakes: [
      'Swinging elbows forward — keep them pinned to your sides.',
      'Letting the cable stack rest at the bottom — keep tension throughout.',
      'Rushing the descent — slow it down to maximize brachialis work.',
      'Rotating the wrists — keep the neutral/hammer grip throughout the movement.',
    ],
    animationKeyframes: [
      'Start: arms extended, rope at bottom, neutral grip.',
      'Curl: forearms rise, elbows stationary, rope approaches shoulders.',
      'Top: peak contraction, hands at shoulder level.',
      'Lower: slow eccentric, arms extend back down.',
    ],
    animationUrl: null,
  },

  // ─── WORKOUT C: ARMS & CORE (home) ─────────────────────────────────────────
  {
    id: 'dumbbell-biceps-curl',
    name: 'Dumbbell Biceps Curl',
    primaryMuscles: ['biceps'],
    equipment: 'dumbbell',
    defaultSets: 4,
    repRange: '10-12',
    tempo: '1s up / 2s down',
    cues: [
      'Stand with dumbbells at your sides, palms facing forward (supinated).',
      'Pin your elbows to your sides — they should not move during the exercise.',
      'Curl the dumbbells up toward your shoulders, twisting slightly outward at the top.',
      'Squeeze the bicep hard at the peak — hold for a beat.',
      'Lower slowly over 2 seconds back to full extension.',
      'Alternate arms or do both simultaneously — both approaches work.',
    ],
    commonMistakes: [
      'Swinging the torso to get the weight up — use strict form.',
      'Elbows drifting forward — they must stay tucked to your sides.',
      'Partial range — come all the way down to full extension.',
      'Rushing the negative — this is where muscle damage (and growth) happens.',
    ],
    animationKeyframes: [
      'Start: arms extended, palms forward.',
      'Curl: dumbbells rise, forearms supinate more, biceps contract.',
      'Top: dumbbells near shoulders, peak squeeze.',
      'Lower: slow controlled descent to full hang.',
    ],
    animationUrl: null,
  },
  {
    id: 'concentration-curl',
    name: 'Concentration Curl',
    primaryMuscles: ['biceps'],
    equipment: 'dumbbell',
    defaultSets: 3,
    repRange: '12',
    tempo: '1s up / 2s down',
    cues: [
      'Sit on a bench or chair, lean forward slightly, and rest your elbow against your inner thigh.',
      'Hold the dumbbell with a supinated (underhand) grip, arm hanging straight.',
      'Curl the dumbbell up toward your shoulder, keeping your upper arm braced against your thigh.',
      'Squeeze the bicep hard at the top — this isolation creates a brutal peak contraction.',
      'Lower slowly over 2 seconds back to full extension.',
      'Complete all reps on one arm, then switch.',
    ],
    commonMistakes: [
      'Bracing against the thigh is just stabilizing — do not use your leg to help lift.',
      'Moving the upper arm off the thigh — defeats the isolation purpose.',
      'Not going to full extension — stretch the bicep fully at the bottom.',
      'Using too heavy a weight — this is an isolation exercise, go lighter.',
    ],
    animationKeyframes: [
      'Start: seated, arm hanging, elbow against inner thigh.',
      'Curl: forearm rises, elbow stays braced, dumbbell rises.',
      'Top: dumbbell near shoulder, bicep peak, hard squeeze.',
      'Lower: slow descent to full extension.',
    ],
    animationUrl: null,
  },

  // ─── CORE EXERCISES ─────────────────────────────────────────────────────────
  {
    id: 'plank',
    name: 'Plank',
    primaryMuscles: ['core'],
    equipment: 'bodyweight',
    defaultSets: 3,
    repRange: '45-60s',
    tempo: 'hold',
    cues: [
      'Start in a push-up position, then lower to your forearms. Elbows directly under shoulders.',
      'Body forms a straight line from head to heels — no sagging hips, no raised butt.',
      'Brace your abs like you are about to take a punch.',
      'Squeeze your glutes and quads — total body tension.',
      'Breathe steadily — do not hold your breath.',
      'Keep your neck neutral — look at a spot on the floor about 6 inches ahead of you.',
    ],
    commonMistakes: [
      'Hips sagging — signals a weak core or fatigue. Reset and rebuild tension.',
      'Hips too high — reduces core challenge, not a proper plank.',
      'Holding breath — focus on steady, rhythmic breathing.',
      'Looking up at the wall — causes neck strain.',
    ],
    animationKeyframes: [
      'Setup: forearms on floor, elbows under shoulders, toes on floor.',
      'Hold position: body straight, core braced, glutes tight.',
      'Breathing: steady rhythmic breath while maintaining tension.',
    ],
    animationUrl: null,
  },
  {
    id: 'dead-bug',
    name: 'Dead Bug',
    primaryMuscles: ['core'],
    equipment: 'bodyweight',
    defaultSets: 3,
    repRange: '10/side',
    tempo: 'controlled',
    cues: [
      'Lie on your back with arms pointing straight up to the ceiling and knees bent at 90° in the air.',
      'Press your lower back firmly into the floor — this is the key cue for the whole exercise.',
      'Slowly lower your right arm overhead and your left leg toward the floor simultaneously.',
      'Lower until just above the floor — do not touch — keeping your lower back pressed down.',
      'Return to the start and repeat on the opposite side (left arm, right leg).',
      'Move slowly and with control — this is about anti-extension core stability.',
    ],
    commonMistakes: [
      'Lower back lifting off the floor — reduce range of motion until you can control it.',
      'Moving too fast — the slow, controlled tempo is the entire point.',
      'Holding your breath — exhale as you extend the limbs.',
      'Not going to full extension — work the full range as control improves.',
    ],
    animationKeyframes: [
      'Start: back on floor, arms up, knees up at 90°.',
      'Extend: opposite arm and leg lower toward floor simultaneously.',
      'Bottom: limbs near floor, back pressed down.',
      'Return: limbs come back to start, switch sides.',
    ],
    animationUrl: null,
  },
  {
    id: 'hollow-body-hold',
    name: 'Hollow Body Hold',
    primaryMuscles: ['core'],
    equipment: 'bodyweight',
    defaultSets: 3,
    repRange: '30-45s',
    tempo: 'hold',
    cues: [
      'Lie on your back and press your lower back into the floor.',
      'Lift your legs and arms off the floor — arms reach overhead, legs out straight.',
      'The goal is to create a "hollow" or "banana" shape — not a flat back, but a slight compression.',
      'Pull your ribcage down toward your hips — this is core compression, not just raising limbs.',
      'Hold the position — it should feel like your entire midsection is working hard.',
      'If too difficult, bend your knees or keep arms by your sides to reduce the lever.',
    ],
    commonMistakes: [
      'Lower back arching off the floor — this is the most common fault. Press that back down.',
      'Legs too high — lower them for more challenge (while keeping back down).',
      'Forgetting the rib-to-hip compression — it is not just a leg raise.',
      'Holding the breath — breathe shallowly but continuously.',
    ],
    animationKeyframes: [
      'Setup: lying flat, about to initiate.',
      'Compression: ribs pull to hips, low back presses into floor.',
      'Hold: arms and legs extended, hollow shape maintained.',
    ],
    animationUrl: null,
  },
  {
    id: 'bicycle-crunch',
    name: 'Bicycle Crunch',
    primaryMuscles: ['core'],
    equipment: 'bodyweight',
    defaultSets: 3,
    repRange: '15/side',
    tempo: 'controlled',
    cues: [
      'Lie on your back with hands lightly behind your head, elbows wide.',
      'Lift your shoulder blades off the floor and raise both knees to 90°.',
      'Rotate your right elbow toward your left knee while extending your right leg out.',
      'Then switch — left elbow to right knee, left leg extends.',
      'The key is rotation, not just crunch — feel your obliques twisting.',
      'Move at a controlled tempo — do not rush, each rep should be deliberate.',
    ],
    commonMistakes: [
      'Pulling on the neck with your hands — hands are just a light guide.',
      'Barely rotating — you need genuine oblique twist, not just elbow to knee.',
      'Going too fast — quality reps beat speed every time.',
      'Lower back arching — keep it pressed to the floor throughout.',
    ],
    animationKeyframes: [
      'Start: shoulders up, both knees at 90°, hands behind head.',
      'Rotate right: right elbow twists to left knee, right leg extends.',
      'Switch: motion reverses — left elbow to right knee.',
      'Continuous cycle: smooth rotation from side to side.',
    ],
    animationUrl: null,
  },
];

export const WORKOUTS: WorkoutDefinition[] = [
  {
    id: 'workout-a-push',
    name: 'Workout A',
    label: 'PUSH',
    location: 'home',
    exerciseIds: [
      'dumbbell-floor-press',
      'dumbbell-shoulder-press',
      'dumbbell-lateral-raise',
      'dumbbell-floor-fly',
      'dumbbell-overhead-triceps-extension',
      'dumbbell-triceps-kickback',
    ],
    miniVersion: [
      'dumbbell-floor-press',
      'dumbbell-shoulder-press',
      'dumbbell-overhead-triceps-extension',
    ],
  },
  {
    id: 'workout-b-pull',
    name: 'Workout B',
    label: 'PULL',
    location: 'gym',
    exerciseIds: [
      'lat-pulldown',
      'seated-cable-row',
      'assisted-pull-up',
      'face-pull',
      'machine-biceps-curl',
      'rope-hammer-curl',
    ],
    miniVersion: [
      'lat-pulldown',
      'seated-cable-row',
      'machine-biceps-curl',
    ],
  },
  {
    id: 'workout-c-arms-core',
    name: 'Workout C',
    label: 'ARMS & CORE',
    location: 'home',
    exerciseIds: [
      'dumbbell-biceps-curl',
      'concentration-curl',
      'dumbbell-overhead-triceps-extension',
      'dumbbell-triceps-kickback',
      'plank',
      'dead-bug',
      'hollow-body-hold',
      'bicycle-crunch',
    ],
    miniVersion: [
      'dumbbell-biceps-curl',
      'dumbbell-overhead-triceps-extension',
      'plank',
    ],
  },
];

export const WEEKLY_SCHEDULE: ScheduleDay[] = [
  {
    dayOfWeek: 0, // Sunday
    label: 'Sunday',
    items: [
      {
        id: 'sun-push',
        type: 'workout',
        label: 'Workout A — Push',
        optional: false,
        workoutId: 'workout-a-push',
      },
      {
        id: 'sun-easy-run',
        type: 'run',
        label: 'Easy run (optional)',
        optional: true,
        distanceKm: 5,
      },
    ],
  },
  {
    dayOfWeek: 1, // Monday
    label: 'Monday',
    items: [
      {
        id: 'mon-pull',
        type: 'workout',
        label: 'Workout B — Pull',
        optional: false,
        workoutId: 'workout-b-pull',
      },
      {
        id: 'mon-core',
        type: 'core',
        label: '10-min core finisher',
        optional: false,
        durationMinutes: 10,
      },
    ],
  },
  {
    dayOfWeek: 2, // Tuesday
    label: 'Tuesday',
    items: [
      {
        id: 'tue-track',
        type: 'run',
        label: 'Track run',
        optional: false,
        distanceKm: 5,
      },
      {
        id: 'tue-core',
        type: 'core',
        label: '10-min core',
        optional: false,
        durationMinutes: 10,
      },
    ],
  },
  {
    dayOfWeek: 3, // Wednesday
    label: 'Wednesday',
    items: [
      {
        id: 'wed-rowing',
        type: 'rowing',
        label: 'Rowing session',
        optional: true,
        backupOptions: [
          { label: 'Easy 5k run', type: 'run', distanceKm: 5 },
          { label: 'Workout A (Push)', type: 'workout', workoutId: 'workout-a-push' },
        ],
      },
    ],
  },
  {
    dayOfWeek: 4, // Thursday
    label: 'Thursday',
    items: [
      {
        id: 'thu-track',
        type: 'run',
        label: 'Track run',
        optional: false,
        distanceKm: 5,
      },
      {
        id: 'thu-arms-core',
        type: 'workout',
        label: 'Workout C — Arms & Core',
        optional: false,
        workoutId: 'workout-c-arms-core',
      },
    ],
  },
  {
    dayOfWeek: 5, // Friday
    label: 'Friday',
    items: [
      {
        id: 'fri-rowing',
        type: 'rowing',
        label: 'Rowing session',
        optional: true,
        backupOptions: [
          { label: 'Easy 5-6k run', type: 'run', distanceKm: 5.5 },
        ],
      },
    ],
  },
  {
    dayOfWeek: 6, // Saturday
    label: 'Saturday',
    items: [
      {
        id: 'sat-parkrun',
        type: 'run',
        label: 'Parkrun (5k)',
        optional: false,
        distanceKm: 5,
      },
      {
        id: 'sat-rowing',
        type: 'rowing',
        label: 'AM Rowing (optional)',
        optional: true,
      },
      {
        id: 'sat-mobility',
        type: 'mobility',
        label: 'PM Mobility session',
        optional: false,
        durationMinutes: 20,
      },
    ],
  },
];

export const EXERCISE_MAP = new Map<string, Exercise>(
  EXERCISES.map((e) => [e.id, e])
);

export const WORKOUT_MAP = new Map<string, WorkoutDefinition>(
  WORKOUTS.map((w) => [w.id, w])
);

export const SCHEDULE_MAP = new Map<number, ScheduleDay>(
  WEEKLY_SCHEDULE.map((d) => [d.dayOfWeek, d])
);
